package com.example.huiyiqiandaotv.beans;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.huiyiqiandaotv.beans.BaoCunBean;
import com.example.huiyiqiandaotv.beans.BenDiRenShuBean;
import com.example.huiyiqiandaotv.beans.MoShengRenBean;
import com.example.huiyiqiandaotv.beans.QianDaoId;
import com.example.huiyiqiandaotv.beans.RenYuanInFo;
import com.example.huiyiqiandaotv.beans.SheBeiInFoBean;
import com.example.huiyiqiandaotv.beans.TanChuangBean;
import com.example.huiyiqiandaotv.beans.ZhuJiBeanH;

import com.example.huiyiqiandaotv.beans.BaoCunBeanDao;
import com.example.huiyiqiandaotv.beans.BenDiRenShuBeanDao;
import com.example.huiyiqiandaotv.beans.MoShengRenBeanDao;
import com.example.huiyiqiandaotv.beans.QianDaoIdDao;
import com.example.huiyiqiandaotv.beans.RenYuanInFoDao;
import com.example.huiyiqiandaotv.beans.SheBeiInFoBeanDao;
import com.example.huiyiqiandaotv.beans.TanChuangBeanDao;
import com.example.huiyiqiandaotv.beans.ZhuJiBeanHDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig baoCunBeanDaoConfig;
    private final DaoConfig benDiRenShuBeanDaoConfig;
    private final DaoConfig moShengRenBeanDaoConfig;
    private final DaoConfig qianDaoIdDaoConfig;
    private final DaoConfig renYuanInFoDaoConfig;
    private final DaoConfig sheBeiInFoBeanDaoConfig;
    private final DaoConfig tanChuangBeanDaoConfig;
    private final DaoConfig zhuJiBeanHDaoConfig;

    private final BaoCunBeanDao baoCunBeanDao;
    private final BenDiRenShuBeanDao benDiRenShuBeanDao;
    private final MoShengRenBeanDao moShengRenBeanDao;
    private final QianDaoIdDao qianDaoIdDao;
    private final RenYuanInFoDao renYuanInFoDao;
    private final SheBeiInFoBeanDao sheBeiInFoBeanDao;
    private final TanChuangBeanDao tanChuangBeanDao;
    private final ZhuJiBeanHDao zhuJiBeanHDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baoCunBeanDaoConfig = daoConfigMap.get(BaoCunBeanDao.class).clone();
        baoCunBeanDaoConfig.initIdentityScope(type);

        benDiRenShuBeanDaoConfig = daoConfigMap.get(BenDiRenShuBeanDao.class).clone();
        benDiRenShuBeanDaoConfig.initIdentityScope(type);

        moShengRenBeanDaoConfig = daoConfigMap.get(MoShengRenBeanDao.class).clone();
        moShengRenBeanDaoConfig.initIdentityScope(type);

        qianDaoIdDaoConfig = daoConfigMap.get(QianDaoIdDao.class).clone();
        qianDaoIdDaoConfig.initIdentityScope(type);

        renYuanInFoDaoConfig = daoConfigMap.get(RenYuanInFoDao.class).clone();
        renYuanInFoDaoConfig.initIdentityScope(type);

        sheBeiInFoBeanDaoConfig = daoConfigMap.get(SheBeiInFoBeanDao.class).clone();
        sheBeiInFoBeanDaoConfig.initIdentityScope(type);

        tanChuangBeanDaoConfig = daoConfigMap.get(TanChuangBeanDao.class).clone();
        tanChuangBeanDaoConfig.initIdentityScope(type);

        zhuJiBeanHDaoConfig = daoConfigMap.get(ZhuJiBeanHDao.class).clone();
        zhuJiBeanHDaoConfig.initIdentityScope(type);

        baoCunBeanDao = new BaoCunBeanDao(baoCunBeanDaoConfig, this);
        benDiRenShuBeanDao = new BenDiRenShuBeanDao(benDiRenShuBeanDaoConfig, this);
        moShengRenBeanDao = new MoShengRenBeanDao(moShengRenBeanDaoConfig, this);
        qianDaoIdDao = new QianDaoIdDao(qianDaoIdDaoConfig, this);
        renYuanInFoDao = new RenYuanInFoDao(renYuanInFoDaoConfig, this);
        sheBeiInFoBeanDao = new SheBeiInFoBeanDao(sheBeiInFoBeanDaoConfig, this);
        tanChuangBeanDao = new TanChuangBeanDao(tanChuangBeanDaoConfig, this);
        zhuJiBeanHDao = new ZhuJiBeanHDao(zhuJiBeanHDaoConfig, this);

        registerDao(BaoCunBean.class, baoCunBeanDao);
        registerDao(BenDiRenShuBean.class, benDiRenShuBeanDao);
        registerDao(MoShengRenBean.class, moShengRenBeanDao);
        registerDao(QianDaoId.class, qianDaoIdDao);
        registerDao(RenYuanInFo.class, renYuanInFoDao);
        registerDao(SheBeiInFoBean.class, sheBeiInFoBeanDao);
        registerDao(TanChuangBean.class, tanChuangBeanDao);
        registerDao(ZhuJiBeanH.class, zhuJiBeanHDao);
    }
    
    public void clear() {
        baoCunBeanDaoConfig.clearIdentityScope();
        benDiRenShuBeanDaoConfig.clearIdentityScope();
        moShengRenBeanDaoConfig.clearIdentityScope();
        qianDaoIdDaoConfig.clearIdentityScope();
        renYuanInFoDaoConfig.clearIdentityScope();
        sheBeiInFoBeanDaoConfig.clearIdentityScope();
        tanChuangBeanDaoConfig.clearIdentityScope();
        zhuJiBeanHDaoConfig.clearIdentityScope();
    }

    public BaoCunBeanDao getBaoCunBeanDao() {
        return baoCunBeanDao;
    }

    public BenDiRenShuBeanDao getBenDiRenShuBeanDao() {
        return benDiRenShuBeanDao;
    }

    public MoShengRenBeanDao getMoShengRenBeanDao() {
        return moShengRenBeanDao;
    }

    public QianDaoIdDao getQianDaoIdDao() {
        return qianDaoIdDao;
    }

    public RenYuanInFoDao getRenYuanInFoDao() {
        return renYuanInFoDao;
    }

    public SheBeiInFoBeanDao getSheBeiInFoBeanDao() {
        return sheBeiInFoBeanDao;
    }

    public TanChuangBeanDao getTanChuangBeanDao() {
        return tanChuangBeanDao;
    }

    public ZhuJiBeanHDao getZhuJiBeanHDao() {
        return zhuJiBeanHDao;
    }

}
